auto: true
server: true

exclude: ["README.md", ".gitignore"]
pygments: true
permalink: /:title/
production_url: http://leandroadacosta.com

title: leandroadacosta.com
author:
   name: Leandro A. da Costa